/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SellersIndexImport } from './routes/sellers/index'
import { Route as ItemsIndexImport } from './routes/items/index'
import { Route as BuyersIndexImport } from './routes/buyers/index'
import { Route as SellersSellerIdImport } from './routes/sellers/$sellerId'
import { Route as BuyersBuyerIdImport } from './routes/buyers/$buyerId'
import { Route as ItemsItemIdIndexImport } from './routes/items/$itemId/index'
import { Route as ItemsItemIdOptionsIndexImport } from './routes/items/$itemId/options/index'
import { Route as ItemsItemIdOptionsOptionIdImport } from './routes/items/$itemId/options/$optionId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SellersIndexRoute = SellersIndexImport.update({
  id: '/sellers/',
  path: '/sellers/',
  getParentRoute: () => rootRoute,
} as any)

const ItemsIndexRoute = ItemsIndexImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRoute,
} as any)

const BuyersIndexRoute = BuyersIndexImport.update({
  id: '/buyers/',
  path: '/buyers/',
  getParentRoute: () => rootRoute,
} as any)

const SellersSellerIdRoute = SellersSellerIdImport.update({
  id: '/sellers/$sellerId',
  path: '/sellers/$sellerId',
  getParentRoute: () => rootRoute,
} as any)

const BuyersBuyerIdRoute = BuyersBuyerIdImport.update({
  id: '/buyers/$buyerId',
  path: '/buyers/$buyerId',
  getParentRoute: () => rootRoute,
} as any)

const ItemsItemIdIndexRoute = ItemsItemIdIndexImport.update({
  id: '/items/$itemId/',
  path: '/items/$itemId/',
  getParentRoute: () => rootRoute,
} as any)

const ItemsItemIdOptionsIndexRoute = ItemsItemIdOptionsIndexImport.update({
  id: '/items/$itemId/options/',
  path: '/items/$itemId/options/',
  getParentRoute: () => rootRoute,
} as any)

const ItemsItemIdOptionsOptionIdRoute = ItemsItemIdOptionsOptionIdImport.update(
  {
    id: '/items/$itemId/options/$optionId',
    path: '/items/$itemId/options/$optionId',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/buyers/$buyerId': {
      id: '/buyers/$buyerId'
      path: '/buyers/$buyerId'
      fullPath: '/buyers/$buyerId'
      preLoaderRoute: typeof BuyersBuyerIdImport
      parentRoute: typeof rootRoute
    }
    '/sellers/$sellerId': {
      id: '/sellers/$sellerId'
      path: '/sellers/$sellerId'
      fullPath: '/sellers/$sellerId'
      preLoaderRoute: typeof SellersSellerIdImport
      parentRoute: typeof rootRoute
    }
    '/buyers/': {
      id: '/buyers/'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersIndexImport
      parentRoute: typeof rootRoute
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsIndexImport
      parentRoute: typeof rootRoute
    }
    '/sellers/': {
      id: '/sellers/'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersIndexImport
      parentRoute: typeof rootRoute
    }
    '/items/$itemId/': {
      id: '/items/$itemId/'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/items/$itemId/options/$optionId': {
      id: '/items/$itemId/options/$optionId'
      path: '/items/$itemId/options/$optionId'
      fullPath: '/items/$itemId/options/$optionId'
      preLoaderRoute: typeof ItemsItemIdOptionsOptionIdImport
      parentRoute: typeof rootRoute
    }
    '/items/$itemId/options/': {
      id: '/items/$itemId/options/'
      path: '/items/$itemId/options'
      fullPath: '/items/$itemId/options'
      preLoaderRoute: typeof ItemsItemIdOptionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buyers/$buyerId': typeof BuyersBuyerIdRoute
  '/sellers/$sellerId': typeof SellersSellerIdRoute
  '/buyers': typeof BuyersIndexRoute
  '/items': typeof ItemsIndexRoute
  '/sellers': typeof SellersIndexRoute
  '/items/$itemId': typeof ItemsItemIdIndexRoute
  '/items/$itemId/options/$optionId': typeof ItemsItemIdOptionsOptionIdRoute
  '/items/$itemId/options': typeof ItemsItemIdOptionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buyers/$buyerId': typeof BuyersBuyerIdRoute
  '/sellers/$sellerId': typeof SellersSellerIdRoute
  '/buyers': typeof BuyersIndexRoute
  '/items': typeof ItemsIndexRoute
  '/sellers': typeof SellersIndexRoute
  '/items/$itemId': typeof ItemsItemIdIndexRoute
  '/items/$itemId/options/$optionId': typeof ItemsItemIdOptionsOptionIdRoute
  '/items/$itemId/options': typeof ItemsItemIdOptionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/buyers/$buyerId': typeof BuyersBuyerIdRoute
  '/sellers/$sellerId': typeof SellersSellerIdRoute
  '/buyers/': typeof BuyersIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/sellers/': typeof SellersIndexRoute
  '/items/$itemId/': typeof ItemsItemIdIndexRoute
  '/items/$itemId/options/$optionId': typeof ItemsItemIdOptionsOptionIdRoute
  '/items/$itemId/options/': typeof ItemsItemIdOptionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buyers/$buyerId'
    | '/sellers/$sellerId'
    | '/buyers'
    | '/items'
    | '/sellers'
    | '/items/$itemId'
    | '/items/$itemId/options/$optionId'
    | '/items/$itemId/options'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buyers/$buyerId'
    | '/sellers/$sellerId'
    | '/buyers'
    | '/items'
    | '/sellers'
    | '/items/$itemId'
    | '/items/$itemId/options/$optionId'
    | '/items/$itemId/options'
  id:
    | '__root__'
    | '/'
    | '/buyers/$buyerId'
    | '/sellers/$sellerId'
    | '/buyers/'
    | '/items/'
    | '/sellers/'
    | '/items/$itemId/'
    | '/items/$itemId/options/$optionId'
    | '/items/$itemId/options/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyersBuyerIdRoute: typeof BuyersBuyerIdRoute
  SellersSellerIdRoute: typeof SellersSellerIdRoute
  BuyersIndexRoute: typeof BuyersIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
  SellersIndexRoute: typeof SellersIndexRoute
  ItemsItemIdIndexRoute: typeof ItemsItemIdIndexRoute
  ItemsItemIdOptionsOptionIdRoute: typeof ItemsItemIdOptionsOptionIdRoute
  ItemsItemIdOptionsIndexRoute: typeof ItemsItemIdOptionsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyersBuyerIdRoute: BuyersBuyerIdRoute,
  SellersSellerIdRoute: SellersSellerIdRoute,
  BuyersIndexRoute: BuyersIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
  SellersIndexRoute: SellersIndexRoute,
  ItemsItemIdIndexRoute: ItemsItemIdIndexRoute,
  ItemsItemIdOptionsOptionIdRoute: ItemsItemIdOptionsOptionIdRoute,
  ItemsItemIdOptionsIndexRoute: ItemsItemIdOptionsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/buyers/$buyerId",
        "/sellers/$sellerId",
        "/buyers/",
        "/items/",
        "/sellers/",
        "/items/$itemId/",
        "/items/$itemId/options/$optionId",
        "/items/$itemId/options/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/buyers/$buyerId": {
      "filePath": "buyers/$buyerId.tsx"
    },
    "/sellers/$sellerId": {
      "filePath": "sellers/$sellerId.tsx"
    },
    "/buyers/": {
      "filePath": "buyers/index.tsx"
    },
    "/items/": {
      "filePath": "items/index.tsx"
    },
    "/sellers/": {
      "filePath": "sellers/index.tsx"
    },
    "/items/$itemId/": {
      "filePath": "items/$itemId/index.tsx"
    },
    "/items/$itemId/options/$optionId": {
      "filePath": "items/$itemId/options/$optionId.tsx"
    },
    "/items/$itemId/options/": {
      "filePath": "items/$itemId/options/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
